### PR TITLE
Allow to use attrs >=17

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by hynek** [comment]
As explained in the other PR, pls pin attrs.

**Comment by hynek** [comment]
Why did you close this?

**Comment by jschueller** [comment]
Ok, I pinned attrs too and maxed out the other dependencies

**Comment by hynek** [comment]
Thanks!

**Comment by jschueller** [comment]
Is there a release planned soonish ?

**Comment by hynek** [comment]
Yeah I think the changes by @jnothman warrant a release once they’re all merged.

**Comment by hynek** [comment]
2.2.0 is on pypi

**Pull request merged**
