### PR TITLE
Support PyDoctor 15.1

### PR DESCRIPTION
**Pull request by hawkowl**
This isn't a released PyDoctor, but it should be soon.

### CODE REVIEW

**Comment by hawkowl** [comment]
This almost certainly breaks reading pydoctor-generated docs before 15.1, but... I'm not sure that's a big deal?

**Comment by hynek** [comment]
I thought you made it work with PyDoctor’s objects.inv?  Home come you had the nicer breakdown?

**Comment by hawkowl** [comment]
No, I just improved the PyDoctor checks to use some stuff I've added to the in-dev version of Pydoctor.

**Comment by hawkowl** [comment]
The failures seem to be unrelated...

**Comment by hynek** [comment]
you could try adding a `passenv = LC_ALL`

**Comment by hynek** [comment]
to tox.ini

**Comment by hawkowl** [comment]
Okay, lets see what it says.

**Comment by hynek** [comment]
flake8 is very related :-P

**Comment by hawkowl** [comment]
Fixed that up.

<sub><sub>(3 is too many blank lines? BLASPHEMY)</sub></sub>

**Comment by hynek** [comment]
@Kapeli does this work for you as expected?

**Comment by Kapeli** [comment]
I've just generated and released the docs for Twisted 15.2.1 using this. Everything seems ok.

Thank you @hawkowl! :+1:

**Comment by hawkowl** [comment]
:tada: :D

**Comment by hynek** [comment]
cool.

you should know, @hawkowl is literally the best.

**Pull request merged**
