### PR TITLE
Update requirements info

### PR DESCRIPTION
**Pull request by DelightRun**
Use `>=` instead of `==` in order to support the latest version of required packages

### CODE REVIEW

**Comment by hynek** [comment]
doc2dash uses explicit pinning on purpose because it’s an application that is ran by a user.  Therefore I want to make sure it runs and I can’t when an update of say lxml suddenly breaks compatibility.  This is the Python way of static linking and I update the dependencies before each upgrade.  Thanks for considering to contribute though!

**Comment by DelightRun** [comment]
I suggest that some packages should be upgrade. Because some of my 
python packages, i.e. Keras, require higher version of those packages 
required by `doc2dash`.

Hynek Schlawack wrote:

**Comment by hynek** [comment]
Keras doesn’t seem to depend on doc2dash in any way.  Are you trying to install everything into your global Python installation?  There are many reasons to not do that: https://hynek.me/articles/virtualenv-lives/

**Comment by DelightRun** [comment]
No, Keras requires six 1.9 while doc2dash requiring six == 1.8.0

Hynek Schlawack wrote:

**Comment by hynek** [comment]
Yes but how is that a problem?  There shouldn’t be the necessity to install them into the same virtualenv unless I’m missing something?  For Python applications like doc2dash I [recommend](https://doc2dash.readthedocs.org/en/2.0.2/installation.html) pipsi: https://github.com/mitsuhiko/pipsi

**Comment by DelightRun** [comment]
Oh, I got it. I didn't use virtualenv...Sorry for distrubbing you

Hynek Schlawack wrote:

**Comment by hynek** [comment]
Good, good.  As a friendly advice: you *really* should start using virtualenv unless you want to face broken Python installations and unnecessary problems like version conflicts in the future.

**Comment by DelightRun** [comment]
Thank you for your advice

Hynek Schlawack wrote:

**Pull request closed without merging**
